# Generated by Django 2.2.3 on 2019-08-01 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_auto_20190801_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='toCompanyName',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
