# Generated by Django 2.2.1 on 2019-08-04 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0003_auto_20190801_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='toCompany',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='toCompany', to='invoice.Company'),
        ),
    ]
