# Generated by Django 2.2.1 on 2019-08-29 04:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('excel_upload', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='excelfile',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
