# Generated by Django 2.2.1 on 2019-08-29 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_upload', '0002_excelfile_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='excelfile',
            name='file_hash',
            field=models.CharField(default=0, max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='excelfile',
            name='uid',
            field=models.CharField(default=0, max_length=32),
            preserve_default=False,
        ),
    ]
